// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicoItem.Repositorio.Infra;

#nullable disable

namespace ServicoItem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ServicoItem.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoItem")
                        .HasColumnType("TEXT");

                    b.HasKey("IdItem");

                    b.ToTable("itens");
                });
#pragma warning restore 612, 618
        }
    }
}
